AttributeError: 'GeneralStats' object has no attribute 'stats'
The thing is that obj.stats is supposed to be in absolutely another obj which is BikeStats. And why there is error with obj attribute obj.stats 0n 54 line but not with the obj.trips_amount for instance on 29